# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.32.0"

[[constraint]]
  branch = "master"
  name = "github.com/gosuri/uitable"

[[constraint]]
  name = "github.com/rakyll/statik"
  version = "0.1.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/ksonnet/kubecfg"
  revision = "8634737e0b22b01bb93ffeb09a195d0a6d71a6e5"

[[constraint]]
  name = "k8s.io/client-go"
  version = "5.0.1"

# Hardcode some packages to the revisions locked in client-go 5.0.1
# See https://github.com/kubernetes/client-go/blob/master/INSTALL.md#dep-not-supported-yet
[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "019ae5ada31de202164b118aee88ee2d14075c31"

[[constraint]]
  name = "k8s.io/api"
  revision = "6c6dac0277229b9e9578c5ca3f74a4345d35cdc2"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "58f6f26e200fa5dfb40c9cd1c83f3e2c860d779d"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/rakyll/statik"
    unused-packages = false
