{{- if .Values.rbac.create -}}
# The cleanup job is necessary to remove "apprepositories" created
# in the bootstrap job or in the web application
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "kubeapps.apprepository-jobs-cleanup.fullname" . }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "-10"
  labels:
    app: {{ template "kubeapps.apprepository-jobs-cleanup.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - kubeapps.com
  resources:
  - apprepositories
  verbs:
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "kubeapps.apprepository-jobs-cleanup.fullname" . }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "-10"
  labels:
    app: {{ template "kubeapps.apprepository-jobs-cleanup.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "kubeapps.apprepository-jobs-cleanup.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kubeapps.apprepository-jobs-cleanup.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
