[package]
name = "pinniped-proxy"
version = "0.1.0"
authors = [
    "Andres Martinez <andresmgot@vmware.com>",
    "Antonio Gamez <agamez@vmware.com>",
    "Michael Nelson <minelson@vmware.com>"
    ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
base64 = "0.13"
hyper = { version = "0.14", features = ["server"] }
hyper-tls = "0.5"
kube = { version = "0.52.0" }
# We explicitly import kube-derive without the schema option to avoid
# requiring the jsonschema for CRDs until
# https://github.com/Arnavion/k8s-openapi/issues/86
# is sorted. AFAICT, the openapi json schema is only required when creating a
# CRD (which we're not).
kube-derive = { version = "0.52.0", default-features = false}
kube-runtime = "0.52.0"
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_17"] }
log = "0.4"
native-tls = "0.2"
openssl = "0.10"
pretty_env_logger = "0.4"
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-native-tls = "0.3"
url = "2.2"

[dev-dependencies]
tokio-test = "0.4"
serial_test = "0.5"
