# Copyright 2023 the Kubeapps contributors.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "oci-catalog"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.9"
prost = "0.11"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1"
futures-core = "0.3"
# To build a statically linked version, will need to use the rusttls rather than
# OS-native, then compile for the linux-musl conditionally with something like
# https://stackoverflow.com/a/75350455 in the Dockerfile to set a target
# linux-musl target specific for the arch.
# reqwest = { version ="0.11", default_features=false, features = ["rustls-tls"] }
reqwest = "0.11"

[build-dependencies]
tonic-build = "0.9"
