[package]
name = "oci-catalog"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.9"
prost = "0.11"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1"
futures-core = "0.3"
reqwest = "0.11"

[build-dependencies]
tonic-build = "0.9"
