# Copyright 2019-2022 the Kubeapps contributors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: integration
  name: integration
spec:
  selector:
    matchLabels:
      run: integration
  template:
    metadata:
      labels:
        run: integration
    spec:
      containers:
        - args:
            - tail
            - -f
            - /dev/null
          image: kubeapps/integration-tests-pw:v1.0.0
          name: integration
          resources:
            requests:
              memory: 300Mi
              cpu: 250m
            limits:
              memory: 600Mi
              cpu: 500m
