## The extra value fields below are currently not included in the chart so as to not document
## experimental functionality until we're ready to include it in the published chart.

## @section kubeappsapis parameters

## KubeappsAPIs parameters
##
featureFlags:
  kubeappsAPIsServer: true

kubeappsapis:
  ## @param kubeappsapis.unsafeUseDemoSA If true, replace the user's credentials by a full-granted demo service account. Just intented for development purposes.
  unsafeUseDemoSA: false
  ## Bitnami Kubeapps-APIs image
  ## ref: https://hub.docker.com/r/bitnami/kubeapps-apis/tags/
  ## @param kubeappsapis.image.registry Kubeapps-APIs image registry
  ## @param kubeappsapis.image.repository Kubeapps-APIs image repository
  ## @param kubeappsapis.image.tag Kubeapps-APIs image tag (immutable tags are recommended)
  ## @param kubeappsapis.image.pullPolicy Kubeapps-APIs image pull policy
  ## @param kubeappsapis.image.pullSecrets Kubeapps-APIs image pull secrets
  ##
  image:
    registry: docker.io
    repository: kubeapps/kubeapps-apis
    tag: latest
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
  replicaCount: 1
  ## @param kubeappsapis.terminationGracePeriodSeconds The grace time period for sig term
  ## ref: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-execution
  ##
  terminationGracePeriodSeconds: 300
  ## @param kubeappsapis.extraEnvVars Array with extra environment variables to add to the KubeappsAPIs container
  ## e.g:
  ## extraEnvVars:
  ##   - name: FOO
  ##     value: "bar"
  ##
  extraEnvVars: []
  ## @param kubeappsapis.extraEnvVarsCM Name of existing ConfigMap containing extra env vars for the KubeappsAPIs container
  ##
  extraEnvVarsCM:
  ## @param kubeappsapis.extraEnvVarsSecret Name of existing Secret containing extra env vars for the KubeappsAPIs container
  ##
  extraEnvVarsSecret:
  ## @param kubeappsapis.containerPort KubeappsAPIs HTTP container port
  ##
  containerPort: 50051
  ## KubeappsAPIs containers' resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ## @param kubeappsapis.resources.limits.cpu The CPU limits for the KubeappsAPIs container
  ## @param kubeappsapis.resources.limits.memory The memory limits for the KubeappsAPIs container
  ## @param kubeappsapis.resources.requests.cpu The requested CPU for the KubeappsAPIs container
  ## @param kubeappsapis.resources.requests.memory The requested memory for the KubeappsAPIs container
  ##
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 25m
      memory: 32Mi
  ## Configure Pods Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  ## @param kubeappsapis.podSecurityContext.enabled Enabled KubeappsAPIs pods' Security Context
  ## @param kubeappsapis.podSecurityContext.fsGroup Set KubeappsAPIs pod's Security Context fsGroup
  ##
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  ## Configure Container Security Context (only main container)
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ## @param kubeappsapis.containerSecurityContext.enabled Enabled KubeappsAPIs containers' Security Context
  ## @param kubeappsapis.containerSecurityContext.runAsUser Set KubeappsAPIs container's Security Context runAsUser
  ## @param kubeappsapis.containerSecurityContext.runAsNonRoot Set KubeappsAPIs container's Security Context runAsNonRoot
  ##
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
  ## Configure extra options for KubeappsAPIs containers' liveness and readiness probes
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
  ## @param kubeappsapis.livenessProbe.enabled Enable livenessProbe
  ## @skip kubeappsapis.livenessProbe.httpGet
  ## @param kubeappsapis.livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
  ## @param kubeappsapis.livenessProbe.periodSeconds Period seconds for livenessProbe
  ## @param kubeappsapis.livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
  ## @param kubeappsapis.livenessProbe.failureThreshold Failure threshold for livenessProbe
  ## @param kubeappsapis.livenessProbe.successThreshold Success threshold for livenessProbe
  ## KubeappsAPIs containers' liveness and readiness probes
  ## ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
  ##
  livenessProbe:
    enabled: false
    httpGet:
      path: /live
      port: 50051
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  ## @param kubeappsapis.readinessProbe.enabled Enable readinessProbe
  ## @skip kubeappsapis.readinessProbe.httpGet
  ## @param kubeappsapis.readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
  ## @param kubeappsapis.readinessProbe.periodSeconds Period seconds for readinessProbe
  ## @param kubeappsapis.readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
  ## @param kubeappsapis.readinessProbe.failureThreshold Failure threshold for readinessProbe
  ## @param kubeappsapis.readinessProbe.successThreshold Success threshold for readinessProbe
  ##
  readinessProbe:
    enabled: false
    httpGet:
      path: /ready
      port: 50051
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  ## @param kubeappsapis.customLivenessProbe Custom livenessProbe that overrides the default one
  ##
  customLivenessProbe: {}
  ## @param kubeappsapis.customReadinessProbe Custom readinessProbe that overrides the default one
  ##
  customReadinessProbe: {}
  ## @param kubeappsapis.lifecycleHooks Custom lifecycle hooks for KubeappsAPIs containers
  ##
  lifecycleHooks: {}
  ## @param kubeappsapis.podLabels Extra labels for KubeappsAPIs pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  ##
  podLabels: {}
  ## @param kubeappsapis.podAnnotations Annotations for KubeappsAPIs pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ##
  podAnnotations: {}
  ## @param kubeappsapis.podAffinityPreset Pod affinity preset. Ignored if `affinity` is set. Allowed values: `soft` or `hard`
  ## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  ##
  podAffinityPreset: ""
  ## @param kubeappsapis.podAntiAffinityPreset Pod anti-affinity preset. Ignored if `affinity` is set. Allowed values: `soft` or `hard`
  ## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  ##
  podAntiAffinityPreset: soft
  ## nodeAffinityPreset Node affinity preset
  ## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
  ##
  nodeAffinityPreset:
    ## @param kubeappsapis.nodeAffinityPreset.type Node affinity preset type. Ignored if `affinity` is set. Allowed values: `soft` or `hard`
    ##
    type: ""
    ## @param kubeappsapis.nodeAffinityPreset.key Node label key to match. Ignored if `affinity` is set
    ##
    key: ""
    ## @param kubeappsapis.nodeAffinityPreset.values Node label values to match. Ignored if `affinity` is set
    ## E.g.
    ## values:
    ##   - e2e-az1
    ##   - e2e-az2
    ##
    values: []
  ## @param kubeappsapis.affinity Affinity for pod assignment
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ## NOTE: kubeappsapis.podAffinityPreset, kubeappsapis.podAntiAffinityPreset, and kubeappsapis.nodeAffinityPreset will be ignored when it's set
  ##
  affinity: {}
  ## @param kubeappsapis.nodeSelector Node labels for pod assignment
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}
  ## @param kubeappsapis.tolerations Tolerations for pod assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations: []
  ## @param kubeappsapis.priorityClassName Priority class name for KubeappsAPIs pods
  ##
  priorityClassName:
  ## @param kubeappsapis.hostAliases Custom host aliases for KubeappsAPIs pods
  ## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
  ##
  hostAliases: []
  ## kubeappsapis service parameters
  ##
  service:
    ## @param kubeappsapis.service.port KubeappsAPIs service HTTP port
    ##
    port: 8080
    ## @param kubeappsapis.service.annotations Additional custom annotations for KubeappsAPIs service
    ##
    annotations: {}
