# This is an example of config file.
# Copy it to `$HOME/monocular/config/monocular.yaml` in order to make the backend pick up the overrides.
repos:
  # Official repositories
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
    source: https://github.com/kubernetes/charts/tree/master/stable
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
    source: https://github.com/kubernetes/charts/tree/master/incubator
  # Add your own repository
  #- name: my-repo-name
  #  url: my-repository-url
  #  source: my-repository-source

# cors:
#   allowed_origins:
#     - my-ui-hostname
#   allowed_headers:
#     - "content-type"
#     - "x-xsrf-token"

# Enables Helm deployment integration
# https://github.com/kubernetes-helm/monocular/tree/master/deployment/monocular#other-configuration-options
releasesEnabled: true
# Enables port forwarding for tiller Connections
# Useful if you are running the app outside of the k8s cluster during development
tillerPortForward: false

# Configure cache refresh interval in sec
cacheRefreshInterval: 3600

mongodb:
  host: mongodb:27017
  database: monocular
